-- 001_phase1_schema.sql
-- Phase 1: Pipeline + Digest (Week 1)
-- Generated by /plan-eng-review on 2026-04-07

-- Sources: RSS feeds and scraping targets
CREATE TABLE sources (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name            TEXT NOT NULL,                         -- "Blockmedia"
  feed_url        TEXT NOT NULL,                         -- RSS endpoint URL
  source_type     TEXT NOT NULL CHECK (source_type IN ('rss', 'html', 'dart', 'fsc', 'telegram')),
  is_active       BOOLEAN NOT NULL DEFAULT true,
  last_fetched_at TIMESTAMPTZ,
  failure_count   INT NOT NULL DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Articles: raw ingested content
CREATE TABLE articles (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  url          TEXT NOT NULL,
  url_hash     TEXT NOT NULL,                         -- MD5(normalizeUrl(url))
  title_hash   TEXT NOT NULL,                         -- MD5(title.trim().toLowerCase())
  source_id    UUID NOT NULL REFERENCES sources(id),
  source_type  TEXT NOT NULL,                         -- denormalized for fast filtering
  raw_title    TEXT NOT NULL,
  raw_content  TEXT NOT NULL,
  fetched_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_articles_url_hash   ON articles(url_hash);
CREATE INDEX idx_articles_title_hash ON articles(title_hash);
CREATE INDEX idx_articles_fetched_at ON articles(fetched_at DESC);

-- Digests: Claude classification output, one row per article
CREATE TABLE digests (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  article_id     UUID NOT NULL REFERENCES articles(id),
  digest_date    DATE NOT NULL DEFAULT CURRENT_DATE,
  summary_ko     TEXT NOT NULL,
  category       TEXT NOT NULL CHECK (category IN ('KRW', 'Global')),
  urgency        TEXT NOT NULL CHECK (urgency IN ('regulatory', 'market', 'other')),
  urgency_score  NUMERIC(4,3) NOT NULL CHECK (urgency_score BETWEEN 0 AND 1),
  expert_level   TEXT NOT NULL CHECK (expert_level IN ('전문', '입문')) DEFAULT '전문',
  confidence     NUMERIC(4,3) NOT NULL CHECK (confidence BETWEEN 0 AND 1),
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (article_id)                                 -- one digest row per article, ever
);

CREATE INDEX idx_digests_digest_date ON digests(digest_date);
CREATE INDEX idx_digests_urgency     ON digests(urgency, urgency_score DESC, confidence DESC);

-- Subscribers: email signups (Phase 2 signup form)
CREATE TABLE subscribers (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email      TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  active     BOOLEAN NOT NULL DEFAULT true
);

-- Pipeline runs: operational log, source of truth for watchdog
CREATE TABLE pipeline_runs (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  run_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  articles_fetched INT NOT NULL DEFAULT 0,
  articles_new     INT NOT NULL DEFAULT 0,
  articles_skipped INT NOT NULL DEFAULT 0,
  digest_sent      BOOLEAN NOT NULL DEFAULT false,
  failed_sources   TEXT[] NOT NULL DEFAULT '{}',
  status           TEXT NOT NULL CHECK (status IN ('running', 'success', 'partial', 'failed')),
  duration_ms      INT
);

CREATE INDEX idx_pipeline_runs_run_at ON pipeline_runs(run_at DESC);

-- Digest sends: idempotency guard against double Vercel cron invocations
CREATE TABLE digest_sends (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  digest_date     DATE NOT NULL UNIQUE,              -- UNIQUE prevents double send
  sent_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  recipient_count INT NOT NULL DEFAULT 0,
  status          TEXT NOT NULL CHECK (status IN ('pending', 'sent', 'failed'))
);

-- Config: tunable parameters without code deploy
CREATE TABLE config (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  key        TEXT NOT NULL UNIQUE,
  value      TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO config (key, value) VALUES
  ('urgency_alert_threshold',    '0.8'),
  ('daily_sms_cap_per_recipient', '3'),
  ('max_articles_per_digest',    '20');

-- ── RLS ──────────────────────────────────────────────────────────────

ALTER TABLE articles      ENABLE ROW LEVEL SECURITY;
ALTER TABLE digests       ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscribers   ENABLE ROW LEVEL SECURITY;
ALTER TABLE sources       ENABLE ROW LEVEL SECURITY;
ALTER TABLE pipeline_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE digest_sends  ENABLE ROW LEVEL SECURITY;
ALTER TABLE config        ENABLE ROW LEVEL SECURITY;

-- articles: public read (web archive), service_role write only
CREATE POLICY "Public read articles"   ON articles FOR SELECT TO anon USING (true);
CREATE POLICY "Service write articles" ON articles FOR ALL    TO service_role USING (true);

-- digests: public read (web archive), service_role write only
CREATE POLICY "Public read digests"    ON digests  FOR SELECT TO anon USING (true);
CREATE POLICY "Service write digests"  ON digests  FOR ALL    TO service_role USING (true);

-- subscribers: anon INSERT only (signup form), service_role full access
CREATE POLICY "Anon subscribe"       ON subscribers FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Service manage subs"  ON subscribers FOR ALL    TO service_role USING (true);

-- operational tables: service_role only (no public access)
CREATE POLICY "Service only sources"  ON sources       FOR ALL TO service_role USING (true);
CREATE POLICY "Service only runs"     ON pipeline_runs FOR ALL TO service_role USING (true);
CREATE POLICY "Service only sends"    ON digest_sends  FOR ALL TO service_role USING (true);
CREATE POLICY "Service only config"   ON config        FOR ALL TO service_role USING (true);
