-- 002_phase3_schema.sql
-- Phase 3: Real-time alerts (3A) + Telegram (3B) + Weekly deep-dive (3C)
-- Apply at Phase 3A start. Depends on 001_phase1_schema.sql.
-- Generated by /plan-eng-review on 2026-04-07

-- Reports: weekly deep-dive drafts and published reports (Phase 3C)
CREATE TABLE reports (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title_ko      TEXT NOT NULL,
  body_ko       TEXT NOT NULL,
  week_of       DATE NOT NULL,
  status        TEXT NOT NULL CHECK (status IN ('draft', 'published')) DEFAULT 'draft',
  publish_token UUID NOT NULL DEFAULT gen_random_uuid(), -- one-time-use; NULL token_used_at = unused
  token_used_at TIMESTAMPTZ,                            -- set atomically on publish; prevents replay
  published_at  TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Alert log: SMS send history, used for per-day cap enforcement (Phase 3A)
CREATE TABLE alert_log (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source_id        UUID REFERENCES sources(id),
  article_id       UUID REFERENCES articles(id),
  event_summary_ko TEXT NOT NULL,
  urgency_score    NUMERIC(4,3) NOT NULL,
  sent_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  delivery_status  TEXT NOT NULL CHECK (delivery_status IN ('sent', 'failed', 'capped'))
  -- 'capped' = daily_sms_cap_per_recipient reached, SMS not sent
);

CREATE INDEX idx_alert_log_sent_at ON alert_log(sent_at DESC);

-- Alert recipients: SMS opt-in list (Phase 3A)
CREATE TABLE alert_recipients (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  phone_number TEXT NOT NULL UNIQUE,
  name         TEXT,
  active       BOOLEAN NOT NULL DEFAULT true,
  sms_opt_in   BOOLEAN NOT NULL DEFAULT true,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── RLS ──────────────────────────────────────────────────────────────
-- All Phase 3 tables: service_role only (no public read)

ALTER TABLE reports          ENABLE ROW LEVEL SECURITY;
ALTER TABLE alert_log        ENABLE ROW LEVEL SECURITY;
ALTER TABLE alert_recipients ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service reports"    ON reports          FOR ALL TO service_role USING (true);
CREATE POLICY "Service alert_log"  ON alert_log        FOR ALL TO service_role USING (true);
CREATE POLICY "Service recipients" ON alert_recipients FOR ALL TO service_role USING (true);
